#!/usr/bin/env node
// Generate src/components/logo-art.tsx from the design system's logo SVGs
// (assets/logo-wordmark.svg, logo-icon.svg), so path data is never
// retyped by hand. Fill becomes currentColor: the Logo component sets the
// colour (ink or white — "colour comes from the ground").
//   node scripts/gen-logo.mjs <assets-dir>
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = process.argv[2];
if (!dir) throw new Error("usage: node scripts/gen-logo.mjs <assets-dir>");
const art = (file) => {
  const svg = readFileSync(join(dir, file), "utf8").replace(/<metadata>[\s\S]*?<\/metadata>/g, "");
  const viewBox = svg.match(/viewBox="([^"]+)"/)[1];
  // Every drawn shape becomes a path; anything unhandled stops the script
  // (a <polygon> once went missing and the wordmark read "COS").
  const shapes = [...svg.matchAll(/<(path|polygon|rect|circle|ellipse|line|polyline)\b([^>]*)>/g)];
  const paths = shapes.map(([, tag, attrs]) => {
    if (tag === "path") return attrs.match(/\bd="([^"]+)"/)[1];
    if (tag === "polygon") {
      const pts = attrs.match(/\bpoints="([^"]+)"/)[1].trim().split(/[\s,]+/);
      const pairs = [];
      for (let i = 0; i < pts.length; i += 2) pairs.push(`${pts[i]},${pts[i + 1]}`);
      return `M${pairs.join("L")}Z`;
    }
    throw new Error(`${file}: <${tag}> not handled — extend gen-logo.mjs`);
  });
  if (!paths.length) throw new Error(`${file}: no shapes`);
  return { viewBox, paths };
};
const word = art("logo-wordmark.svg");
const icon = art("logo-icon.svg");
const out = `// Generated by scripts/gen-logo.mjs from the COSX Design System 3.0
// logo artwork. Do not edit — regenerate.
export const WORDMARK = ${JSON.stringify(word)} as const;
export const LOOP = ${JSON.stringify(icon)} as const;
`;
writeFileSync(new URL("../src/components/logo-art.ts", import.meta.url), out);
console.log(`wordmark ${word.viewBox} (${word.paths.length} paths) · loop ${icon.viewBox} (${icon.paths.length} paths)`);
